apiVersion: v1
kind: BuildConfig
metadata:
  name: spring-boot-hello-world-pipeline
  labels:
    name: spring-boot-hello-world-pipeline
spec:
  source:
    git:
      uri: "https://github.com/clevandowski/spring-boot-hello-world.git"
      ref: jenkinsfile
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: Jenkinsfile
