kind: BuildConfig
apiVersion: v1
metadata:
  name: spring-boot-hello-world-pipeline
  labels:
    name: spring-boot-hello-world-pipeline
spec:
  strategy:
    type: JenkinsPipeline
    jenkinsPipelineStrategy:
      jenkinsfile: |-
        node('maven') {
          stage('build') {
            openshiftBuild(buildConfig: 'spring-boot-hello-world', showBuildLogs: 'true')
          }
          stage('deploy-development') {
            openshiftDeploy(deploymentConfig: 'spring-boot-hello-world')
          }
          stage('validation') {
            input message: 'Valider ?', ok: 'Oui'
          }
          stage('deploy-integration') {
            openshiftDeploy(deploymentConfig: 'spring-boot-hello-world', namespace: 'integration')
          }
        }
